import descriptions from "./descriptions";

const rules = [
    { 
      term: "Ability Check", 
      translation: "Prova di Caratteristica (Abilità)",
      pagePhb: ["10", "360"],
      pagePhbIt: ["7", "12", "173-179", "186"],
      pageDmg: ["27"],
      pageDmgIt: ["247-238", "245", "263-264"],
      source: "D&D 2024",
      description: descriptions["ability check"],
    },
    { 
      term: "Ability Modifier", 
      translation: "Modificatore Caratteristica",
      pagePhb: ["10", "360"],
      pagePhbIt: ["7"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["ability modifier"],
    },
    { 
      term: "Ability Score", 
      translation: "Punteggio di Caratteristica", 
      pagePhb: ["10", "360"],
      pagePhbIt: ["7", "12-13", "173"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["ability score"],
    },
        { 
          term: "Strength", 
          translation: "Forza", 
          pagePhb: ["10"],
          pagePhbIt: ["12", "175-176"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["strength"],
        },
        { 
          term: "Dexterity", 
          translation: "Destrezza", 
          pagePhb: ["10"],
          pagePhbIt: ["12", "176-177"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["dexterity"],
        },
        { 
          term: "Constitution", 
          translation: "Costituzione", 
          pagePhb: ["10"],
          pagePhbIt: ["12", "177"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["constitution"],
        },
        { 
          term: "Intelligence", 
          translation: "Intelligenza", 
          pagePhb: ["10"],
          pagePhbIt: ["12", "178"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["intelligence"],
        },
        { 
          term: "Wisdom", 
          translation: "Saggezza", 
          pagePhb: ["10"],
          pagePhbIt: ["12", "178"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["wisdom"],
        },
        { 
          term: "Charisma", 
          translation: "Carisma", 
          pagePhb: ["10"],
          pagePhbIt: ["12", "178-179"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["charisma"],
        },
    { 
      term: "Action", 
      translation: "Azione",
      pagePhb: ["15", "360-377"],
      pagePhbIt: ["189", "192-193"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["action"],
    },
        { 
          term: "Attack Action", 
          translation: "Azione di Attacco",
          pagePhb: ["361"],
          pagePhbIt: ["192-193"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["action"],
        },
        { 
          term: "Dash Action", 
          translation: "Azione di Scatto", 
          pagePhb: ["365"],
          pagePhbIt: ["193"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["action"],
        },
        { 
          term: "Disengage Action", 
          translation: "Azione di Disimpegno", 
          pagePhb: ["366"],
          pagePhbIt: ["192"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["action"],
        },
        { 
          term: "Dodge Action", 
          translation: "Azione di Schivata", 
          pagePhb: ["366"],
          pagePhbIt: ["193"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["action"],
        },
        { 
          term: "Help Action", 
          translation: "Azione di Aiuto", 
          pagePhb: ["368"],
          pagePhbIt: ["192"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["action"],
        },
        { 
          term: "Hide Action", 
          translation: "Azione di Nascondersi", 
          pagePhb: ["368"],
          pagePhbIt: ["192"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["action"],
        },
        { 
          term: "Influence Action", 
          translation: "Azione di Influenza?", 
          pagePhb: ["369"],
          pagePhbIt: ["193"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["action"],
        },
        { 
          term: "Magic Action", 
          translation: "Azione di Magia?", 
          pagePhb: ["371"],
          pagePhbIt: ["193"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["action"],
        },
        { 
          term: "Ready Action", 
          translation: "Azione di Prepararsi", 
          pagePhb: ["372"],
          pagePhbIt: ["192-193"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["action"],
        },
        { 
          term: "Search Action", 
          translation: "Azione di Cercare", 
          pagePhb: ["373"],
          pagePhbIt: ["192"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["action"],
        },
        { 
          term: "Study Action", 
          translation: "Azione di Studio?", 
          pagePhb: ["375"],
          pagePhbIt: ["193"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["action"],
        },
        { 
          term: "Utilize Action", 
          translation: "Azione di Utilizzo?", 
          pagePhb: ["377"],
          pagePhbIt: ["193"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["action"],
        },
    { 
      term: "Advantage", 
      translation: "Vantaggio",
      pagePhb: ["12", "360"],
      pagePhbIt: ["7", "173"],
      pageDmg: ["29"],
      pageDmgIt: ["239-240"],
      source: "D&D 2024",
      description: descriptions["advantage"],
    },
    { 
      term: "Alignment", 
      translation: "Allineamento",
      pagePhb: ["39", "360"],
      pagePhbIt: ["122"],
      pageDmg: ["51"],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["alignment"],
    },
    { 
      term: "Ammunition, property", 
      translation: "Munizioni, proprietà",
      pagePhb: ["213"],
      pagePhbIt: ["146-147"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["ammunition, property"],
    },
    { 
      term: "Area of Effect", 
      translation: "Area di Effetto",
      pagePhb: ["361"],
      pagePhbIt: ["204-205"],
      pageDmg: ["44"],
      pageDmgIt: ["249-251"],
      source: "D&D 2024",
      description: descriptions["area of effect"],
    },
    { 
      term: "Armor Class (AC)", 
      translation: "Classe Armatura (CA)",
      pagePhb: ["12", "41", "361"],
      pagePhbIt: ["7", "14", "144", "177"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["armor class"],
    },
    { 
      term: "Attack", 
      translation: "Attacco",
      pagePhb: ["15"],
      pagePhbIt: ["14", "193-196"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["area of effect"],
    },
    { 
      term: "Attack Roll", 
      translation: "Tiro per Colpire",
      pagePhb: ["12", "361"],
      pagePhbIt: ["7", "14", "176", "177", "194"],
      pageDmg: ["29"],
      pageDmgIt: ["235", "238-239"],
      source: "D&D 2024",
      description: descriptions["attack roll"],
    },
    { 
      term: "Attitude", 
      translation: "Atteggiamento",
      pagePhbPhb: ["361"],
      pagePhbIt: [""],
      pageDmg: ["32"],
      pageDmgIt: ["244"],
      source: "D&D 2024",
      description: descriptions["attitude"],
    },
        { 
          term: "Friendly Attitude", 
          translation: "Atteggiamento Amichevole",
          pagePhbPhb: ["367"],
          pagePhbIt: [""],
          pageDmg: ["32"],
          pageDmgIt: ["244"],
          source: "D&D 2024",
          description: descriptions["attitude"],
        },
        { 
          term: "Hostile Attitude", 
          translation: "Atteggiamento Ostile",
          pagePhbPhb: ["368"],
          pagePhbIt: [""],
          pageDmg: ["32"],
          pageDmgIt: ["244"],
          source: "D&D 2024",
          description: descriptions["attitude"],
        },
        { 
          term: "Indifferent Attitude", 
          translation: "Atteggiamento Indifferente",
          pagePhbPhb: ["369"],
          pagePhbIt: [""],
          pageDmg: ["32"],
          pageDmgIt: ["244"],
          source: "D&D 2024",
          description: descriptions["attitude"],
        },
    { 
      term: "Attunement", 
      translation: "Sintonia",
      pagePhbPhb: ["232", "361"],
      pagePhbIt: [""],
      pageDmg: ["217"],
      pageDmgIt: ["136-138"],
      source: "D&D 2024",
      description: descriptions["attunement"],
    },
    { 
      term: "Background", 
      translation: "Background",
      pagePhbPhb: ["177"],
      pagePhbIt: ["11-14", "125-147"],
      pageDmg: ["55"],
      pageDmgIt: ["26", "279"],
      source: "D&D 2024",
      description: descriptions["background"],
    },
        { 
          term: "Acolyte", 
          translation: "Accolito",
          pagePhbPhb: ["178"],
          pagePhbIt: ["127"],
          source: "D&D 2024",
          description: descriptions["background"],
        },
        { 
          term: "Artisan", 
          translation: "Artigiano",
          pagePhbPhb: ["178"],
          pagePhbIt: ["128-129"],
          source: "D&D 2024",
          description: descriptions["background"],
        },
        { 
          term: "Charlatan", 
          translation: "Ciarlatano",
          pagePhbPhb: ["179"],
          pagePhbIt: ["129-130"],
          source: "D&D 2024",
          description: descriptions["background"],
        },
        { 
          term: "Criminal", 
          translation: "Criminale",
          pagePhbPhb: ["179"],
          pagePhbIt: ["130-131"],
          source: "D&D 2024",
          description: descriptions["background"],
        },
        { 
          term: "Entertainer", 
          translation: "Intrattenitore",
          pagePhbPhb: ["180"],
          pagePhbIt: ["135-136"],
          source: "D&D 2024",
          description: descriptions["background"],
        },
        { 
          term: "Farmer", 
          translation: "Contadino?",
          pagePhbPhb: ["180"],
          pagePhbIt: [""],
          source: "D&D 2024",
          description: descriptions["background"],
        },
        { 
          term: "Guard", 
          translation: "Guardia?",
          pagePhbPhb: ["181"],
          pagePhbIt: [""],
          source: "D&D 2024",
          description: descriptions["background"],
        },
        { 
          term: "Guide", 
          translation: "Guida?",
          pagePhbPhb: ["181"],
          pagePhbIt: [""],
          source: "D&D 2024",
          description: descriptions["background"],
        },
        { 
          term: "Hermit", 
          translation: "Eremita",
          pagePhbPhb: ["182"],
          pagePhbIt: ["131-132"],
          source: "D&D 2024",
          description: descriptions["background"],
        },
        { 
          term: "Merchant", 
          translation: "Mercante?",
          pagePhbPhb: ["182"],
          pagePhbIt: [""],
          source: "D&D 2024",
          description: descriptions["background"],
        },
        { 
          term: "Noble", 
          translation: "Nobile",
          pagePhbPhb: ["183"],
          pagePhbIt: ["138-139"],
          source: "D&D 2024",
          description: descriptions["background"],
        },
        { 
          term: "Sage", 
          translation: "Sapiente",
          pagePhbPhb: ["183"],
          pagePhbIt: ["139-140"],
          source: "D&D 2024",
          description: descriptions["background"],
        },
        { 
          term: "Sailor", 
          translation: "Marinaio",
          pagePhbPhb: ["184"],
          pagePhbIt: ["136-137"],
          source: "D&D 2024",
          description: descriptions["background"],
        },
        { 
          term: "Scribe", 
          translation: "Scriba?",
          pagePhbPhb: ["184"],
          pagePhbIt: [""],
          source: "D&D 2024",
          description: descriptions["background"],
        },
        { 
          term: "Soldier", 
          translation: "Soldato",
          pagePhbPhb: ["184"],
          pagePhbIt: ["140-141"],
          source: "D&D 2024",
          description: descriptions["background"],
        },
        { 
          term: "Wayfarer", 
          translation: "Forestiero?",
          pagePhbPhb: ["185"],
          pagePhbIt: ["133-135"],
          source: "D&D 2024",
          description: descriptions["background"],
        },
    { 
      term: "Bonus Action", 
      translation: "Azione Bonus", 
      pagePhb: ["362"],
      pagePhbIt: ["189"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["bonus action"],
    },
    { 
      term: "Carrying Capacity", 
      translation: "Capacità di Trasporto", 
      pagePhb: ["362"],
      pagePhbIt: ["176"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["carrying capacity"],
    },
    { 
      term: "Challenge Rating (CR)", 
      translation: "Grado di Sfida (GS)", 
      pagePhb: ["363"],
      pagePhbIt: ["189"],
      pageDmg: ["343"],
      pageDmgIt: ["82", "92", "274-275", "279", "306-309"],
      source: "D&D 2024",
      description: descriptions["challenge rating"],
    },
    { 
      term: "Combat", 
      translation: "Combattimento", 
      pagePhb: ["23-27"],
      pagePhbIt: ["8", "189-198"],
      pageDmg: ["42"],
      pageDmgIt: ["247-252", "270-273"],
      source: "D&D 2024",
      description: descriptions["combat"],
    },
    { 
      term: "Component", 
      translation: "Componente", 
      pagePhb: ["236-237"],
      pagePhbIt: ["203"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["component"],
    },
    { 
      term: "Concentration", 
      translation: "Concentrazione", 
      pagePhb: ["363"],
      pagePhbIt: ["203-204"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["component"],
    },
    { 
      term: "Condition", 
      translation: "Condizione", 
      pagePhb: ["29", "363"],
      pagePhbIt: ["290-292"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["condition"],
    },
        { 
          term: "Blinded", 
          translation: "Accecato", 
          pagePhb: ["361"],
          pagePhbIt: ["290-292"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["condition"],
        },
        { 
          term: "Charmed", 
          translation: "Affascinato", 
          pagePhb: ["363"],
          pagePhbIt: ["290-292"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["condition"],
        },
        { 
          term: "Deafened", 
          translation: "Assordato", 
          pagePhb: ["365"],
          pagePhbIt: ["290-292"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["condition"],
        },
        { 
          term: "Exhaustion", 
          translation: "Indebolimento", 
          pagePhb: ["366"],
          pagePhbIt: ["290-292"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["condition"],
        },
        { 
          term: "Frightened", 
          translation: "Spaventato", 
          pagePhb: ["367"],
          pagePhbIt: ["290-292"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["condition"],
        },
        { 
          term: "Grappled", 
          translation: "Afferrato", 
          pagePhb: ["367"],
          pagePhbIt: ["290-292"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["condition"],
        },
        { 
          term: "Immunity", 
          translation: "Invulnerabilità", 
          pagePhb: ["369"],
          pagePhbIt: ["290-292"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["condition"],
        },
        { 
          term: "Incapacitated", 
          translation: "Incapacitato", 
          pagePhb: ["369"],
          pagePhbIt: ["290-292"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["condition"],
        },
        { 
          term: "Invisible", 
          translation: "Invisibile", 
          pagePhb: ["370"],
          pagePhbIt: ["290-292"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["condition"],
        },
        { 
          term: "Paralyzed", 
          translation: "Paralizzato", 
          pagePhb: ["371"],
          pagePhbIt: ["290-292"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["condition"],
        },
        { 
          term: "Petrified", 
          translation: "Pietrificato", 
          pagePhb: ["372"],
          pagePhbIt: ["290-292"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["condition"],
        },
        { 
          term: "Poisoned", 
          translation: "Avvelenato", 
          pagePhb: ["372"],
          pagePhbIt: ["290-292"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["condition"],
        },
        { 
          term: "Prone", 
          translation: "Prono", 
          pagePhb: ["372"],
          pagePhbIt: ["290-292"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["condition"],
        },
        { 
          term: "Restrained", 
          translation: "Trattenuto", 
          pagePhb: ["373"],
          pagePhbIt: ["290-292"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["condition"],
        },
        { 
          term: "Stunned", 
          translation: "Stordito", 
          pagePhb: ["376"],
          pagePhbIt: ["290-292"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["condition"],
        },
        { 
          term: "Unconscious", 
          translation: "Privo di Sensi", 
          pagePhb: ["377"],
          pagePhbIt: ["290-292"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["condition"],
        },
    { 
      term: "Construct (creature type)", 
      translation: "Costrutto (tipo di creatura)", 
      pagePhb: ["364"],
      pagePhbIt: [""],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["construct creature type"],
    },    
    { 
      term: "Cover", 
      translation: "Copertura", 
      pagePhb: ["25", "364"],
      pagePhbIt: ["196"],
      pageDmg: ["45"],
      pageDmgIt: ["251", "272"],
      source: "D&D 2024",
      description: descriptions["cover"],
    },
        { 
          term: "Half Cover", 
          translation: "Mezza Copertura",
          pagePhb: ["26"],
          pagePhbIt: ["196"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["cover"],
        },
        { 
          term: "Three-Quarters Cover", 
          translation: "Tre Quarti di Copertura",
          pagePhb: ["26"],
          pagePhbIt: ["196"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["cover"],
        },
        { 
          term: "Total Cover", 
          translation: "Copertura Totale",
          pagePhb: ["26"],
          pagePhbIt: ["196"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["cover"],
        },
    { 
      term: "Crawling", 
      translation: "Strisciare", 
      pagePhb: ["364"],
      pagePhbIt: ["182", "191"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["crawling"],
    },
    { 
      term: "Critical Hit", 
      translation: "Colpo Critico", 
      pagePhb: ["27", "364"],
      pagePhbIt: ["196"],
      pageDmg: [""],
      pageDmgIt: ["249"],
      source: "D&D 2024",
      description: descriptions["critical hit"],
    },
    { 
      term: "Currency", 
      translation: "Valuta", 
      pagePhb: ["213"],
      pagePhbIt: ["143"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["currency"],
    },
    { 
      term: "Curse", 
      translation: "Maledizione", 
      pagePhb: ["364"],
      pagePhbIt: [""],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["curse rule"],
    },
    { 
      term: "Damage", 
      translation: "Danno", 
      pagePhb: ["9", "27", "364"],
      pagePhbIt: ["14", "196-197"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["damage rule"],
    },
    { 
      term: "Damage Roll", 
      translation: "Tiro per i Danni", 
      pagePhb: ["27", "364"],
      pagePhbIt: ["14", "176-177", "196"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["damage roll"],
    },
    { 
      term: "Damage Threshold", 
      translation: "Soglia di Danno", 
      pagePhb: ["364"],
      pagePhbIt: [""],
      pageDmg: ["247"],
      pageDmgIt: ["247"],
      source: "D&D 2024",
      description: descriptions["damage threshold"],
    },
    { 
      term: "Damage Type", 
      translation: "Tipi di Danno", 
      pagePhb: ["28", "365"],
      pagePhbIt: [""],
      pageDmg: [""],
      pageDmgIt: ["247"],
      source: "D&D 2024",
      description: descriptions["damage type"],
    },
        { 
          term: "Acid damage", 
          translation: "Danni da Acido", 
          pagePhb: ["365"],
          pagePhbIt: ["196"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["acid damage"],
        },
        { 
          term: "Bludgeoning damage", 
          translation: "Danni Contundenti", 
          pagePhb: ["365"],
          pagePhbIt: ["196"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["bludgeoning damage"],
        },
        { 
          term: "Cold Damage", 
          translation: "Danni da Freddo", 
          pagePhb: ["365"],
          pagePhbIt: ["196"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["cold damage"],
        },
        { 
          term: "Fire Damage", 
          translation: "Danni da Fuoco", 
          pagePhb: ["365"],
          pagePhbIt: ["196"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["fire damage"],
        },
        { 
          term: "Force Damage", 
          translation: "Danni da Forza", 
          pagePhb: ["365"],
          pagePhbIt: ["196"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["fire damage"],
        },
        { 
          term: "Lightning damage", 
          translation: "Danni da Fulmine", 
          pagePhb: ["365"],
          pagePhbIt: ["196"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["lightning damage"],
        },
        { 
          term: "Necrotic Damage", 
          translation: "Danni Necrotici", 
          pagePhb: ["365"],
          pagePhbIt: ["196"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["necrotic damage"],
        },
        { 
          term: "Piercing Damage", 
          translation: "Danni Perforanti", 
          pagePhb: ["365"],
          pagePhbIt: ["196"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["piercing damage"],
        },
        { 
          term: "Poison Damage", 
          translation: "Danni da Veleno", 
          pagePhb: ["365"],
          pagePhbIt: ["197"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["poison damage"],
        },
        { 
          term: "Psychic Damage", 
          translation: "Danni Psichici", 
          pagePhb: ["365"],
          pagePhbIt: ["196"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["psychic damage"],
        },
        { 
          term: "Radiant Damage", 
          translation: "Danni Radiosi", 
          pagePhb: ["365"],
          pagePhbIt: ["197"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["radiant damage"],
        },
        { 
          term: "Slashing Damage", 
          translation: "Danni Taglienti", 
          pagePhb: ["365"],
          pagePhbIt: ["197"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["slashing damage"],
        },
        { 
          term: "Thunder Damage", 
          translation: "Danni da Tuono", 
          pagePhb: ["365"],
          pagePhbIt: ["197"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["thunder damage"],
        },
    { 
      term: "Death", 
      translation: "Morte", 
      pagePhb: ["28", "365"],
      pagePhbIt: ["197"],
      pageDmg: ["62"],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["death rule"],
    },
        { 
          term: "Instant Death", 
          translation: "Morte Istantanea", 
          pagePhb: ["28"],
          pagePhbIt: ["197"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["death rule"],
        },
        { 
          term: "Massive Damage", 
          translation: "Danno Massiccio", 
          pagePhb: ["28"],
          pagePhbIt: ["193"],
          pageDmg: [""],
          pageDmgIt: ["273"],
          source: "D&D 2024",
          description: descriptions["death rule"],
        },
    { 
      term: "Death Saving Throw", 
      translation: "Tiro Salvezza Contro Morte", 
      pagePhb: ["28", "365"],
      pagePhbIt: ["197"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["death saving throw"],
    },
    { 
      term: "Difficult Terrain", 
      translation: "Terreno Difficile", 
      pagePhb: ["24", "366"],
      pagePhbIt: ["182", "190"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["difficult terrain"],
    },
    { 
      term: "Difficulty Class (DC)", 
      translation: "Classe Difficoltà (CD)",
      pagePhb: ["361"],
      pagePhbIt: ["7", "174"],
      pageDmg: ["29"],
      pageDmgIt: ["238-239"],
      source: "D&D 2024",
      description: descriptions["difficulty class"],
    },
    { 
      term: "Disadvantage", 
      translation: "Svantaggio",
      pagePhb: ["12", "366"],
      pagePhbIt: ["7", "173"],
      pageDmg: ["29"],
      pageDmgIt: ["239-240"],
      source: "D&D 2024",
      description: descriptions["disadvantage"],
    },
    { 
      term: "Equipment", 
      translation: "Equipaggiamento",
      pagePhb: ["213"],
      pagePhbIt: ["14", "125"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["equipment"],
    },
    { 
      term: "Expertise", 
      translation: "Maestria?",
      pagePhb: ["367"],
      pagePhbIt: [""],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["expertise"],
    },
    { 
      term: "Feat", 
      translation: "Talento",
      pagePhb: ["199"],
      pagePhbIt: ["165-170"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["feat rule"],
    },
    { 
      term: "Grappled (condition)", 
      translation: "Afferrato (condizione)",
      pagePhb: ["367"],
      pagePhbIt: ["195"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["grappled"],
    },
    { 
      term: "Grappling", 
      translation: "Afferrato (condizione)",
      pagePhb: ["367"],
      pagePhbIt: ["195"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["grappling"],
    },
    { 
      term: "Hazard", 
      translation: "Danni Ambientali?",
      pagePhb: ["20", "368"],
      pagePhbIt: [""],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["hazard"],
    },
    { 
      term: "Healing", 
      translation: "Guarigione",
      pagePhb: ["28", "368"],
      pagePhbIt: ["197"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["healing"],
    },
        { 
          term: "Stabilized", 
          translation: "Stabile",
          pagePhb: ["29"],
          pagePhbIt: ["197"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["healing"],
        },
        { 
          term: "Stabilizing a character", 
          translation: "Stabilizzare creatura",
          pagePhb: ["29"],
          pagePhbIt: ["197"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["healing"],
        },
    { 
      term: "Heroic Inspiration", 
      translation: "Ispirazione Eroica?",
      pagePhb: ["13", "368"],
      pagePhbIt: ["124-125"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["heroic inspiration"],
    },
    { 
      term: "Hiding", 
      translation: "Nascondersi",
      pagePhb: ["19"],
      pagePhbIt: ["177"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["hiding"],
    },
    { 
      term: "Hit Dice", 
      translation: "Dadi Vita",
      pagePhb: ["41", "368"],
      pagePhbIt: ["12"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["hit dice"],
    },
    { 
      term: "Hit Points", 
      translation: "Punti Ferita",
      pagePhb: ["27", "368"],
      pagePhbIt: ["177"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["hit points"],
    },
        { 
          term: "Temporary Hit Points", 
          translation: "Punti Ferita Temporanei",
          pagePhb: ["29", "376"],
          pagePhbIt: ["177"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["temporary hit points"],
        },
    { 
      term: "Hover", 
      translation: "Fluttuare",
      pagePhb: ["368"],
      pagePhbIt: [""],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["hover"],
    },  
    { 
      term: "Immunity", 
      translation: "Attacco in Mischia",
      pagePhb: ["28", "369"],
      pagePhbIt: ["195"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["immunity"],
    },
    { 
      term: "Initiative", 
      translation: "Iniziativa",
      pagePhbPhb: ["23", "369"],
      pagePhbIt: ["177", "189"],
      pageDmg: ["42"],
      pageDmgIt: ["247", "270-271"],
      source: "D&D 2024",
      description: descriptions["initiative"],
    },
    { 
      term: "Interacting with objects", 
      translation: "Interagire con oggetti ",
      pagePhbPhb: ["19"],
      pagePhbIt: ["185"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["interacting with objects"],
    },
    { 
      term: "Jumping", 
      translation: "Saltare",
      pagePhb: ["370"],
      pagePhbIt: ["182", "190"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["jumping"],
    },
        { 
          term: "High Jump", 
          translation: "Salto in Alto",
          pagePhb: ["369"],
          pagePhbIt: ["182", "190"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["jumping"],
        },
        { 
          term: "Long Jump", 
          translation: "Salto in Lungo",
          pagePhb: ["370"],
          pagePhbIt: ["182", "190"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["jumping"],
        },
    { 
      term: "Light", 
      translation: "Luce", 
      pagePhb: ["19"],
      pagePhbIt: ["183"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["light"],
    },
        { 
          term: "Heavily Obscured", 
          translation: "Pesantemente Oscurato",
          pagePhb: ["19", "368"],
          pagePhbIt: ["183"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["light"],
        },
        { 
          term: "Lightly Obscured", 
          translation: "Leggermente Oscurato",
          pagePhb: ["19", "368"],
          pagePhbIt: ["183"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["light"],
        },
        { 
          term: "Darkness", 
          translation: "Oscurità", 
          pagePhb: ["19", "365"],
          pagePhbIt: ["183"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["light"],
        },
        { 
          term: "Dim Light", 
          translation: "Luce Fioca", 
          pagePhb: ["19", "366"],
          pagePhbIt: ["183"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["light"],
        },
        { 
          term: "Bright Light", 
          translation: "Luce Intensa", 
          pagePhb: ["19", "362"],
          pagePhbIt: ["183"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["light"],
        },
    { 
      term: "Language", 
      translation: "Linguaggio",
      pagePhbPhb: ["37"],
      pagePhbIt: ["17", "123", "125"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["language"],
    },
        {
          term: "Abyssal",
          translation: "Abissale",
          pagePhbPhb: ["37"],
          pagePhbIt: ["17", "123", "125"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["language"],
        },
        {
          term: "Celestial",
          translation: "Celestiale",
          pagePhbPhb: ["37"],
          pagePhbIt: ["17", "123", "125"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["language"],
        },
        {
          term: "Common",
          translation: "Comune",
          pagePhbPhb: ["37"],
          pagePhbIt: ["17", "123", "125"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["language"],
        },
        {
          term: "Common Sign Language",
          translation: "Linguaggio dei Segni in Comune?",
          pagePhbPhb: ["37"],
          pagePhbIt: ["17", "123", "125"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["language"],
        },
        {
          term: "Deep Speech",
          translation: "Linguaggio Profondo",
          pagePhbPhb: ["37"],
          pagePhbIt: ["17", "123", "125"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["language"],
        },
        { 
          term: "Draconic", 
          translation: "Draconico",
          pagePhbPhb: ["37"],
          pagePhbIt: ["17", "123", "125"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["language"],
        },
        { 
          term: "Druidic", 
          translation: "Druidico",
          pagePhbPhb: ["37"],
          pagePhbIt: ["17", "123", "125"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["language"],
        },
        {
          term: "Dwarvish",
          translation: "Nanico",
          pagePhbPhb: ["37"],
          pagePhbIt: ["17", "123", "125"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["language"],
        },
        {
          term: "Elvish",
          translation: "Elfico",
          pagePhbPhb: ["37"],
          pagePhbIt: ["17", "123", "125"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["language"],
        },
        {
          term: "Giant",
          translation: "Gigante",
          pagePhbPhb: ["37"],
          pagePhbIt: ["17", "123", "125"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["language"],
        },
        {
          term: "Gnomish",
          translation: "Gnomesco",
          pagePhbPhb: ["37"],
          pagePhbIt: ["17", "123", "125"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["language"],
        },
        {
          term: "Goblin",
          translation: "Goblin",
          pagePhbPhb: ["37"],
          pagePhbIt: ["17", "123", "125"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["language"],
        },
        {
          term: "Halfling",
          translation: "Halfling",
          pagePhbPhb: ["37"],
          pagePhbIt: ["17", "123", "125"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["language"],
        },
        {
          term: "Infernal",
          translation: "Infernale",
          pagePhbPhb: ["37"],
          pagePhbIt: ["17", "123", "125"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["language"],
        },
        {
          term: "Orc",
          translation: "Orchesco",
          pagePhbPhb: ["37"],
          pagePhbIt: ["17", "123", "125"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["language"],
        },
        {
          term: "Primordial",
          translation: "Primordiale",
          pagePhbPhb: ["37"],
          pagePhbIt: ["17", "123", "125"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["language"],
        },
        {
          term: "Sylvan",
          translation: "Silvano",
          pagePhbPhb: ["37"],
          pagePhbIt: ["17", "123", "125"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["language"],
        },
        { 
          term: "Thieves' Cant", 
          translation: "Gergo Ladresco",
          pagePhbPhb: ["37"],
          pagePhbIt: ["17", "123", "125"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["language"],
        },
        {
          term: "Undercommon",
          translation: "Sottocomune",
          pagePhbPhb: ["37"],
          pagePhbIt: ["17", "123", "125"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["language"],
        },
    { 
      term: "Level advancement", 
      translation: "Avanzamento di livello",
      pagePhbPhb: ["41"],
      pagePhbIt: ["15"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["level advancement"],
    },
    { 
      term: "Lifestyle Expense", 
      translation: "Avanzamento di livello",
      pagePhbPhb: ["230"],
      pagePhbIt: ["157-158", "187"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["lifestyle expense"],
    },
        { 
          term: "Aristocratic (lifestyle)", 
          translation: "Aristocratico (stile di vita)",
          pagePhbPhb: ["231"],
          pagePhbIt: ["157-158", "187"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["lifestyle expense"],
        },
        { 
          term: "Comfortable (lifestyle)", 
          translation: "Agiato (stile di vita)",
          pagePhbPhb: ["231"],
          pagePhbIt: ["157-158", "187"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["lifestyle expense"],
        },
        { 
          term: "Modest (lifestyle)", 
          translation: "Modesto (stile di vita)",
          pagePhbPhb: ["231"],
          pagePhbIt: ["157-158", "187"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["lifestyle expense"],
        },
        { 
          term: "Poor (lifestyle)", 
          translation: "Povero (stile di vita)",
          pagePhbPhb: ["231"],
          pagePhbIt: ["157-158", "187"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["lifestyle expense"],
        },
        { 
          term: "Squalid (lifestyle)", 
          translation: "Squallido (stile di vita)",
          pagePhbPhb: ["231"],
          pagePhbIt: ["157-158", "187"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["lifestyle expense"],
        },
        { 
          term: "Wealthy (lifestyle)", 
          translation: "Ricco (stile di vita)",
          pagePhbPhb: ["231"],
          pagePhbIt: ["157-158", "187"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["lifestyle expense"],
        },
        { 
          term: "Wretched (lifestyle)", 
          translation: "Miserabile (stile di vita)",
          pagePhbPhb: ["230"],
          pagePhbIt: ["157-158", "187"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["lifestyle expense"],
        },
    { 
      term: "Lifestyle Expense", 
      translation: "Avanzamento di livello",
      pagePhbPhb: ["230"],
      pagePhbIt: ["157-158", "187"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["lifestyle expense"],
    },
    { 
      term: "Magical Effect", 
      translation: "Effetto Magico", 
      pagePhb: ["371"],
      pagePhbIt: ["201"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["magical effect"],
    },
    { 
      term: "Magic Item", 
      translation: "Effetto Magico", 
      pagePhb: ["232"],
      pagePhbIt: ["144"],
      pageDmg: ["216-227"],
      pageDmgIt: ["128-130", "133", "135-227"],
      source: "D&D 2024",
      description: descriptions["magic item"],
    },
    { 
      term: "Mastery Property", 
      translation: "Proprietà di Maestria?", 
      pagePhb: ["214"],
      pagePhbIt: [""],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["mastery property"],
    },
    { 
      term: "Melee Attack", 
      translation: "Attacco in Mischia",
      pagePhb: ["26"],
      pagePhbIt: ["195"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["attack"],
    },
    { 
      term: "Mount", 
      translation: "Cavalcatura", 
      pagePhb: ["26-27", "229"],
      pagePhbIt: ["201"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["mount"],
    },
    { 
      term: "Movement", 
      translation: "Movimento", 
      pagePhb: ["24-26"],
      pagePhbIt: ["181-183", "190-192"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["movement"],
    },
    { 
      term: "Multiclassing", 
      translation: "Multiclasse", 
      pagePhb: ["44"],
      pagePhbIt: ["163-164"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["multiclassing"],
    },
    { 
      term: "Object", 
      translation: "Oggetto", 
      pagePhb: ["20", "371"],
      pagePhbIt: ["185"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["object"],
    },
    { 
      term: "Occupied Space", 
      translation: "Spazio Occupato", 
      pagePhb: ["371"],
      pagePhbIt: [""],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["occupied space"],
    },
    { 
      term: "Opportunity Attack", 
      translation: "Attacco di Opportunità",
      pagePhb: ["26", "361"],
      pagePhbIt: ["195"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["opportunity attack"],
    },
    { 
      term: "Passive Perception", 
      translation: "Percezione Passiva", 
      pagePhb: ["40", "372"],
      pagePhbIt: ["175"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["passive perception"],
    },
    { 
      term: "Position", 
      translation: "Posizione", 
      pagePhb: ["24"],
      pagePhbIt: [""],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["position"],
    },
    { 
      term: "Proficiency", 
      translation: "Competenza", 
      pagePhb: ["13-14", "213", "220", "372"],
      pagePhbIt: ["11-12", "14", "155"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["proficiency"],
    },
        { 
          term: "Proficiency Bonus", 
          translation: "Bonus Competenza", 
          pagePhb: ["11", "13"],
          pagePhbIt: ["14-15", "173-174", "194"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["proficiency bonus"],
        },
    { 
      term: "Range", 
      translation: "Gittata", 
      pagePhb: ["26", "236"],
      pagePhbIt: ["147", "195"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["range"],
    },
    { 
      term: "Ranged Attack", 
      translation: "Attacco a Distanza",
      pagePhb: ["26"],
      pagePhbIt: ["195"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["attack"],
    },
    { 
      term: "Reach", 
      translation: "Portata", 
      pagePhb: ["26"],
      pagePhbIt: ["195"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["reach"],
    },
    { 
      term: "Reaction", 
      translation: "Reazione", 
      pagePhb: ["15", "372"],
      pagePhbIt: ["190"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["reaction"],
    },
    { 
      term: "Rest", 
      translation: "Riposare",
      pagePhb: ["367"],
      pagePhbIt: ["186"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["rest"],
    },
        { 
          term: "Short Rest", 
          translation: "Riposo Breve",
          pagePhb: ["367"],
          pagePhbIt: ["186"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["rest"],
        },
        { 
          term: "Long Rest", 
          translation: "Riposo Lungo",
          pagePhb: ["367"],
          pagePhbIt: ["186"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["rest"],
        },
    { 
      term: "Ritual", 
      translation: "Rituale", 
      pagePhb: ["373"],
      pagePhbIt: ["201-202"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["ritual"],
    },
    { 
      term: "Round Down", 
      translation: "Arrotondare", 
      pagePhb: ["373"],
      pagePhbIt: ["7"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["round down"],
    },
    { 
      term: "Saving Throw", 
      translation: "Tiro Salvezza", 
      pagePhb: ["11", "373"],
      pagePhbIt: ["7", "12", "179", "205"],
      pageDmg: ["29"],
      pageDmgIt: ["238-239"],
      source: "D&D 2024",
      description: descriptions["saving throw"],
    },
    { 
      term: "Size", 
      translation: "Taglia",
      pagePhb: ["25", "374"],
      pagePhbIt: ["176", "191-192"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["size"],
    },
        { 
          term: "Gargantuan", 
          translation: "Mastodontica",
          pagePhb: ["25"],
          pagePhbIt: ["191"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["gargantuan"],
        },
        { 
          term: "Huge", 
          translation: "Enorme",
          pagePhb: ["25"],
          pagePhbIt: ["191"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["huge"],
        },
        { 
          term: "Large", 
          translation: "Grande",
          pagePhb: ["25"],
          pagePhbIt: ["191"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["large"],
        },
        { 
          term: "Medium", 
          translation: "Media",
          pagePhb: ["25"],
          pagePhbIt: ["191"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["medium"],
        },
        { 
          term: "Small", 
          translation: "Piccola",
          pagePhb: ["25"],
          pagePhbIt: ["191"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["small"],
        },
        { 
          term: "Tiny", 
          translation: "Minuscola",
          pagePhb: ["25"],
          pagePhbIt: ["191"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["tiny"],
        },
    { 
      term: "Shape-shifting", 
      translation: "Mutare Forma",
      pagePhb: ["373"],
      pagePhbIt: ["176", "191-192"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["shape-shifting"],
    },
    { 
    term: "Skill",
    translation: "Abilità",
    pagePhb: ["374"],
    pagePhbIt: ["174-175"],
    pageDmg: [""],
    pageDmgIt: [""],
    source: "D&D 2024",
    description: descriptions["skill"],
    },
        { 
          term: "Acrobatics",
          translation: "Acrobazia",
          pagePhb: ["14"],
          pagePhbIt: ["177"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["acrobatics"]
        },
        { 
          term: "Animal Handling",
          translation: "Addestrare Animali",
          pagePhb: ["14"],
          pagePhbIt: ["178"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["animal handling"]
        },
        { 
          term: "Arcana",
          translation: "Arcano",
          pagePhb: ["14"],
          pagePhbIt: ["178"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["arcana"]
        },
        { 
          term: "Athletics",
          translation: "Atletica",
          pagePhb: ["14"],
          pagePhbIt: ["175"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["athletics"]
        },
        { 
          term: "Deception",
          translation: "Inganno",
          pagePhb: ["14"],
          pagePhbIt: ["178"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["deception"]
        },
        { 
          term: "History",
          translation: "Storia",
          pagePhb: ["14"],
          pagePhbIt: ["178"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["history"]
        },
        { 
          term: "Insight",
          translation: "Intuizione",
          pagePhb: ["14"],
          pagePhbIt: ["178"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["insight"]
        },
        { 
          term: "Intimidation",
          translation: "Intimidire",
          pagePhb: ["14"],
          pagePhbIt: ["179"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["intimidation"]
        },
        { 
          term: "Investigation",
          translation: "Indagare",
          pagePhb: ["14"],
          pagePhbIt: ["178"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["investigation"]
        },
        { 
          term: "Medicine",
          translation: "Medicina",
          pagePhb: ["14"],
          pagePhbIt: ["178"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["medicine"]
        },
        { 
          term: "Nature",
          translation: "Natura",
          pagePhb: ["14"],
          pagePhbIt: ["178"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["nature"]
        },
        { 
          term: "Perception",
          translation: "Percezione",
          pagePhb: ["14"],
          pagePhbIt: ["178"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["perception"]
        },
        { 
          term: "Performance",
          translation: "Intrattenere",
          pagePhb: ["14"],
          pagePhbIt: ["179"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["performance"]
        },
        { 
          term: "Persuasion",
          translation: "Persuasione",
          pagePhb: ["14"],
          pagePhbIt: ["179"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["persuasion"]
        },
        { 
          term: "Religion",
          translation: "Religione",
          pagePhb: ["14"],
          pagePhbIt: ["178"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["religion"]
        },
        { 
          term: "Sleight of Hand",
          translation: "Rapidità di Mano",
          pagePhb: ["14"],
          pagePhbIt: ["177"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["sleight of hand"]
        },
        { 
          term: "Stealth",
          translation: "Furtività",
          pagePhb: ["14"],
          pagePhbIt: ["177"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["stealth"]
        },
        { 
          term: "Survival",
          translation: "Sopravvivenza",
          pagePhb: ["14"],
          pagePhbIt: ["178"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["survival"]
        },
    { 
      term: "Social Interaction", 
      translation: "Interazione Sociale",
      pagePhbPhb: ["16"],
      pagePhbIt: ["8", "185-186"],
      pageDmg: ["32"],
      pageDmgIt: ["244-246"],
      source: "D&D 2024",
      description: descriptions["social interaction"],
    },    
    { 
      term: "Space", 
      translation: "Spazio",
      pagePhb: ["371", "373"],
      pagePhbIt: ["191-192"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["space"],
    },
    { 
      term: "Special Senses", 
      translation: "Sensi Speciali",
      pagePhb: ["19"],
      pagePhbIt: [""],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["special senses"],
    },
        { 
          term: "Blindsight", 
          translation: "Vista Cieca",
          pagePhb: ["361"],
          pagePhbIt: ["183"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["blindsight"],
        },
        { 
          term: "Darkvision", 
          translation: "Scurovisione",
          pagePhb: ["365"],
          pagePhbIt: ["183"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["darkvision"],
        },
        { 
          term: "Tremorsense", 
          translation: "Percezione Tellurica",
          pagePhb: ["377"],
          pagePhbIt: [""],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["tremorsense"],
        },
        { 
          term: "Truesight", 
          translation: "Vista Pura",
          pagePhb: ["377"],
          pagePhbIt: ["185"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["truesight"],
        },
    { 
      term: "Speed", 
      translation: "Velocità",
      pagePhb: ["374"],
      pagePhbIt: [""],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["speed"],
    },
        { 
          term: "Burrow", 
          translation: "Scavare",
          pagePhb: ["362"],
          pagePhbIt: [""],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["burrow"],
        },
        { 
          term: "Climb", 
          translation: "Scalare",
          pagePhb: ["363"],
          pagePhbIt: ["182", "190"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["climb"],
        },
        { 
          term: "Fly", 
          translation: "Volare",
          pagePhb: ["367"],
          pagePhbIt: ["191"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["fly"],
        },
        { 
          term: "Swim", 
          translation: "Nuotare",
          pagePhb: ["376"],
          pagePhbIt: ["182", "190"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["swim"],
        },
    { 
      term: "Spell", 
      translation: "Incantesimo",
      pagePhb: ["235-238", "374"],
      pagePhbIt: ["201-205"],
      pageDmg: ["59"],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["spell"],
    },
    { 
      term: "Starting at higher levels", 
      translation: "Iniziare a livelli superiori",
      pagePhb: ["43"],
      pagePhbIt: ["176", "191-192"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["starting at higher levels"],
    },
    { 
      term: "Squeezing", 
      translation: "Stringersi",
      pagePhb: ["24", "366"],
      pagePhbIt: ["92"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["squeezing"],
    },
    { 
      term: "Surprise", 
      translation: "Sorpresa",
      pagePhb: ["23", "376"],
      pagePhbIt: ["189"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["surprise"],
    },
    { 
      term: "Target", 
      translation: "Bersaglio",
      pagePhb: ["376"],
      pagePhbIt: ["204"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["target"],
    },
    { 
      term: "Unarmed Strike", 
      translation: "Attacco Senz'Armi",
      pagePhb: ["377"],
      pagePhbIt: ["195"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["unarmed strike"],
    },
    { 
      term: "Unoccupied Space", 
      translation: "Spazio Libero",
      pagePhb: ["377"],
      pagePhbIt: ["191-192"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["unoccupied space"],
    },
    { 
      term: "Vulnerability", 
      translation: "Vulnerabilità",
      pagePhb: ["28", "377"],
      pagePhbIt: ["197"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["vulnerabilità"],
    },
    { 
      term: "Weapon", 
      translation: "Arma", 
      pagePhb: ["213-214", "369", "377"],
      pagePhbIt: ["14", "146-149"],
      pageDmg: [""],
      pageDmgIt: [""],
      source: "D&D 2024",
      description: descriptions["weapon"],
    },
        { 
          term: "Improvised Weapon", 
          translation: "Arma improvvisata",
          pagePhb: ["369"],
          pagePhbIt: ["147-148"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["weapon"],
        },
        { 
          term: "Martial Weapon", 
          translation: "Arma Marziale",
          pagePhb: ["213"],
          pagePhbIt: ["146"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["weapon"],
        },
        { 
          term: "Melee Weapon", 
          translation: "Arma da Mischia",
          pagePhb: ["213"],
          pagePhbIt: ["14", "146", "149", "195"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["weapon"],
        },
        { 
          term: "Ranged Weapon", 
          translation: "Arma a Distanza",
          pagePhb: ["213"],
          pagePhbIt: ["14", "146", "149", "195"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["weapon"],
        },
        { 
          term: "Simple Weapon", 
          translation: "Arma Semplice",
          pagePhb: ["213"],
          pagePhbIt: ["146"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["weapon"],
        },
        { 
          term: "Weapon Mastery Property", 
          translation: "Proprietà di Maestria dell'Arma?",
          pagePhb: ["214"],
          pagePhbIt: [""],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["weapon"],
        },
        { 
          term: "Weapon Proficiency", 
          translation: "Competenza nelle Armi",
          pagePhb: ["213"],
          pagePhbIt: ["147-148"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["weapon"],
        },
        { 
          term: "Weapon Property", 
          translation: "Proprietà delle Armi", 
          pagePhb: ["213"],
          pagePhbIt: ["146-194"],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["weapon"],
        },
        { 
          term: "Wearing Items", 
          translation: "Indossare Oggetti",
          pagePhb: ["233"],
          pagePhbIt: [""],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["wearing items"],
        },
        { 
          term: "Wielding Items", 
          translation: "Impugnare Oggetti",
          pagePhb: ["233"],
          pagePhbIt: [""],
          pageDmg: [""],
          pageDmgIt: [""],
          source: "D&D 2024",
          description: descriptions["wielding items"],
        },
  ];
  
  export default rules;